version: '3'

volumes:
  local_postgres_data: {}

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
    volumes:
      - ./:/app/:z
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=ask-ai
      - POSTGRES_PASSWORD=insecure
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"

  requirements:
    image: python:3.11
    profiles:
      - utils
    volumes:
      - ./:/app/:z
