# Generated by Django 3.2.19 on 2023-06-25 14:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "llm_model",
                    models.CharField(
                        blank=True,
                        choices=[("gpt-3.5-turbo", "gpt-3.5-turbo")],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "user_prompt",
                    models.CharField(blank=True, default="", max_length=4096),
                ),
                ("raw_user_prompt", models.JSONField(blank=True, null=True)),
                ("raw_ai_response", models.JSONField(blank=True, null=True)),
                (
                    "ai_response",
                    models.CharField(blank=True, default="", max_length=4096),
                ),
                ("flagged_sensitive", models.BooleanField(default=False)),
                ("user_prompt_moderated", models.BooleanField(default=False)),
                ("ai_response_moderated", models.BooleanField(default=False)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conversation.chat",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
