# Generated by Django 3.2.19 on 2023-06-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0002_chat_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="ai_response",
            field=models.TextField(blank=True, default=""),
        ),
    ]
