# Generated by Django 3.2.19 on 2023-06-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0003_alter_prompt_ai_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="answers_useful",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="chat_ended",
            field=models.BooleanField(default=False),
        ),
    ]
