# Generated by Django 3.2.19 on 2023-06-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0004_auto_20230628_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="confirm_info_retained",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chat",
            name="confirm_not_sensitive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chat",
            name="confirm_results_to_be_checked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chat",
            name="purpose",
            field=models.TextField(blank=True, default=""),
        ),
    ]
