# Generated by Django 3.2.20 on 2023-07-15 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0005_auto_20230628_1047"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="answers_useful",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="confirm_info_retained",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="confirm_not_sensitive",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="confirm_results_to_be_checked",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="purpose",
        ),
    ]
