# Generated by Django 3.2.20 on 2023-07-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0006_auto_20230715_1805"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="api_call_error",
            field=models.BooleanField(default=False),
        ),
    ]
