# Generated by Django 3.2.20 on 2023-07-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0007_prompt_api_call_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="cost_input_dollars",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="prompt",
            name="cost_output_dollars",
            field=models.FloatField(default=0),
        ),
    ]
