# Generated by Django 4.2.6 on 2023-10-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0008_auto_20230729_1946"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prompt",
            old_name="flagged_sensitive",
            new_name="potentially_sensitive",
        ),
        migrations.AddField(
            model_name="prompt",
            name="user_confirmed_not_sensitive",
            field=models.BooleanField(default=False),
        ),
    ]
