# Generated by Django 4.2.6 on 2023-10-31 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0010_remove_prompt_raw_ai_response_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="prompt",
            options={"ordering": ["created_at"]},
        ),
    ]
