# Generated by Django 4.2.7 on 2023-11-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0011_alter_chat_options_alter_prompt_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="llm_model",
            field=models.CharField(blank=True, choices=[("GPT35_TURBO", "gpt-3.5-turbo")], default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="user_prompt",
            field=models.TextField(blank=True, default=""),
        ),
    ]
