# Generated by Django 4.2.7 on 2023-11-27 12:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0012_alter_prompt_llm_model_alter_prompt_user_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "satisfaction",
                    models.CharField(
                        choices=[
                            ("VERY_DISSATISFIED", "Very dissatisfied"),
                            ("DISSATISFIED", "Dissatisfied"),
                            ("NO_OPINION", "No opinion"),
                            ("SATISFIED", "Satisfied"),
                            ("VERY_SATISFIED", "Very satisfied"),
                        ],
                        max_length=254,
                    ),
                ),
                ("improve_the_service", models.TextField(blank=True)),
                ("take_part_in_user_research", models.BooleanField(choices=[(True, "Yes"), (False, "No")])),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
    ]
