# Generated by Django 4.2.7 on 2023-11-28 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0013_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="chat_ended",
        ),
    ]
