# Generated by Django 4.2.8 on 2023-12-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0015_remove_empty_chats"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="completed_declaration",
            field=models.BooleanField(default=False),
        ),
    ]
