# Generated by Django 4.2.8 on 2023-12-13 13:41
from django.db import migrations


def create_data_downloader_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    group = Group.objects.create(name="Data download")
    group.save()


def delete_data_downloader_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.delete(name="Data download")


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0016_user_completed_declaration"),
    ]

    operations = [migrations.RunPython(create_data_downloader_group, reverse_code=delete_data_downloader_group)]
