# Generated by Django 4.2.9 on 2024-01-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0018_prompt_tokens_input_prompt_tokens_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="llm_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GPT35_TURBO", "gpt-3.5-turbo"),
                    ("GPT35_TURBO_1106", "gpt-3.5-turbo-1106"),
                    ("GPT35_TURBO_0125", "gpt-3.5-turbo-0125"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
